"""empty message

Revision ID: 167427b4758b
Revises: ea9b515ceb27
Create Date: 2022-05-20 10:47:23.031796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '167427b4758b'
down_revision = 'ea9b515ceb27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('rstp_port', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cameras', 'rstp_port')
    # ### end Alembic commands ###
