"""empty message

Revision ID: 3a8b6433716c
Revises: 167427b4758b
Create Date: 2022-05-20 13:58:47.898285

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3a8b6433716c'
down_revision = '167427b4758b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('camera_type', sa.String(length=200), nullable=False))
    op.add_column('cameras', sa.Column('camera_status', sa.Integer(), nullable=False))
    op.drop_column('cameras', 'camrea_status')
    op.drop_column('cameras', 'camrea_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('camrea_type', mysql.VARCHAR(length=200), nullable=False))
    op.add_column('cameras', sa.Column('camrea_status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('cameras', 'camera_status')
    op.drop_column('cameras', 'camera_type')
    # ### end Alembic commands ###
